In [1]:
import numpy as np
from onezone import imf as imf
from onezone import zone as zone
from onezone import star as Star
import pickle

In [2]:
Star.SE_TABLE.interpolate([1.0, 0.01], 'Teff')

5804.5692926777883

In [3]:
sim = zone.Zone( M_gas = 2.0E6, M_DM = 1.0E9)

In [4]:
sim.parameters['dt_dump']       = 2.0
sim.parameters['dt_summary']    = 0
sim.parameters['cycle_dump']    = 0
sim.parameters['cycle_summary'] = 1

In [5]:
sim.evolve(3.0)

/home/emerick/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/emerick/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/emerick/code/onezone/data_tables.py:77: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if  c == flag or id == flag:


Writing full dump output as output_name_0000 at time t = 0.0000
Writing full dump output as output_name_0001 at time t = 2.0000


In [6]:
star1 = sim.stars[0]

In [13]:
print sim._cycle_number

3


In [7]:
np.size(sim.stars)

33697

In [8]:
sim.stars[0].id

0

In [9]:
m      = [x.M for x in sim.stars if (x.M > 30.0)*(x.M<40.0)]
pid    = [x.id for x in sim.stars if x.M > 20.0]
status = [x.properties['status'] for x in sim.stars]

In [10]:
#print m, pid
for i in np.arange(len(pid)):
    massive_star = sim.stars[pid[i]]

    print massive_star.properties['Q0'], massive_star.properties['Q1']


2.6933422638e+48 7.90534308487e+47
1.98847810561e+48 5.37632800842e+47
0.0 0.0
5.45413665946e+48 1.83652352543e+48
1.14397878972e+49 4.31081909631e+48
2.39041248262e+48 6.81330892756e+47
2.82464333357e+49 1.18329067074e+49
2.91241718944e+48 8.69917718549e+47
7.5962985601e+48 2.67943194535e+48
2.91241718944e+48 8.69917718549e+47
5.03025073146e+48 1.67140906392e+48
3.03616418794e+49 1.28368619654e+49
2.91241718944e+48 8.69917718549e+47
4.57339877055e+48 1.49385867317e+48
7.98546357482e+48 2.83596827007e+48
5.52785979485e+48 1.86527360768e+48
1.14397878972e+49 4.31081909631e+48
2.48810306826e+48 7.16470501457e+47
1.66399859713e+49 6.59712977498e+48
1.17046263521e+49 4.42568969491e+48
2.96944909368e+48 8.90634852554e+47
1.05197958283e+49 3.8934372639e+48
4.27008948198e+48 1.3762488186e+48
7.98546357482e+48 2.83596827007e+48
3.76605347185e+48 1.18471996028e+48
3.09500870875e+49 1.31132001472e+49
2.2497599076e+48 6.30877032955e+47
0.0 0.0
4.57339877055e+48 1.49385867317e+48
1.98847810561e+48

In [11]:
Star.RAD_TABLE.x

OrderedDict([('temperature',
              array([ 27500.,  30000.,  32500.,  35000.,  37500.,  40000.,  42500.,
                      45000.,  47500.,  50000.,  52500.,  55000.])),
             ('surface_gravity',
              array([  1000.        ,   1778.27941004,   3162.27766017,   5623.4132519 ,
                      10000.        ,  17782.79410039,  31622.77660168,  56234.13251903])),
             ('metallicity',
              array([  0.00000000e+00,   1.00000000e-03,   1.00000000e-02,
                       2.00000000e-02,   3.33333333e-02,   1.00000000e-01,
                       2.00000000e-01,   5.00000000e-01,   1.00000000e+00,
                       2.00000000e+00]))])

In [12]:
star_parse = lambda name, star_list : [x.properties[name] for x in star_list]
star_parse('L_FUV',sim.stars)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0070561089479151e+32,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.2416562063021898e+33,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0